# Generated by Django 4.2 on 2023-05-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='donations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organization',
            name='donations',
            field=models.IntegerField(default=0),
        ),
    ]
