# Generated by Django 4.2 on 2023-05-15 05:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=100)),
                ('rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='resources/')),
                ('classno', models.IntegerField(validators=[django.core.validators.MaxValueValidator(16)])),
                ('orgn', models.BooleanField(default=False)),
                ('helperid', models.UUIDField(blank=True, null=True)),
                ('address', models.CharField(max_length=100)),
                ('donated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=100)),
                ('rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='resources/')),
                ('orgn', models.BooleanField(default=False)),
                ('helperid', models.UUIDField(blank=True, null=True)),
                ('address', models.CharField(max_length=100)),
                ('donated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Miscellaneous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=100)),
                ('rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='resources/')),
                ('orgn', models.BooleanField(default=False)),
                ('helperid', models.UUIDField(blank=True, null=True)),
                ('address', models.CharField(max_length=100)),
                ('donated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MiscReq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('whyneed', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=100)),
                ('accepted', models.BooleanField(default=False)),
                ('sent', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='resources.miscellaneous')),
            ],
        ),
        migrations.CreateModel(
            name='ClothesReq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('whyneed', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=100)),
                ('accepted', models.BooleanField(default=False)),
                ('sent', models.BooleanField(default=False)),
                ('clothes', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='resources.clothes')),
            ],
        ),
        migrations.CreateModel(
            name='BookReq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('whyneed', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=100)),
                ('accepted', models.BooleanField(default=False)),
                ('sent', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='resources.book')),
            ],
        ),
    ]
